# The Weisfeiler-Lehman Isomorphism Test

The Weisfeiler-Lehman Isomorphism Test, also called WL-Test, is a classical result from the graph theory. It is an heuristic to find out if two graphs are isomorphic. The problem of the graph isomorphism does not have a definitive solution in polinomial time yet, making some people say it may be NP-Complete. The WL-Test offers one alternative that allows us to estimate it.

However, since this is an heuristic, the test is not perfect. Therefore, it fail in some simple cases and because of that new versions of this test were proposed.

In this notebook we will explore a little about the theory of the test and implement it in its classical form and also some newer versions.

In [3]:
!pip3 install networkx

Defaulting to user installation because normal site-packages is not writeable
Collecting networkx
  Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 5.1 MB/s eta 0:00:000m eta 0:00:01[36m0:00:01
WARNING: Error parsing requirements for typing-extensions: [Errno 2] No such file or directory: '/mnt-homes/kraken/jsalas/.local/lib/python3.10/site-packages/typing_extensions-4.14.1.dist-info/METADATA'
Installing collected packages: networkx
Successfully installed networkx-3.4.2

In [1]:
import networkx as nx
def load_graph(file, punctuation=False):
    G = nx.read_graphml(file).to_undirected()
    if not punctuation:
        not_wanted = [".", ",", ";", ":"]
        punct_nodes = [n for n in G.nodes() if G.nodes[n].get("form") in not_wanted]
        G.remove_nodes_from(punct_nodes)

    G.graph['phrase'] = G.graph.get('phrase', 'No phrase found')
    

    return G

# New implementation (gpt)

In [2]:
from __future__ import annotations
from collections import defaultdict
from collections import Counter

# ---------- WL over trees ----------
def wl_tree_signature(G: nx.Graph) -> str:
    """
    1-WL color refinement on an (unlabeled) tree G.
    Returns a canonical signature string usable as a dict key.
    """
    # Relabel to 0..n-1 for array-friendly processing
    G = nx.relabel.convert_node_labels_to_integers(G, ordering="sorted")  # keeps attrs by default
    n = G.number_of_nodes()

    # adjacency as list of lists for speed
    adj = [list(G.neighbors(v)) for v in range(n)]  # neighbors() yields iterator.  [oai_citation:6‡networkx.org](https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.neighbors.html?utm_source=chatgpt.com)
    colors = [0] * n
    tmp = [None] * n
    i = 0
    signature = ""
    while True:      
        
        for v in range(n):
            neigh_cols = sorted(colors[u] for u in adj[v])
            tmp[v] = str(colors[v]) +"_"+ str(tuple(neigh_cols))
        # compress tuples → small ints
        mapping = {}
        next_c = 0
        new_colors = [0] * n
        for v in range(n):
            key = tmp[v]
            #print(f"key is {key}")
            if key not in mapping:
                mapping[key] = next_c
                next_c += 1
            new_colors[v] = mapping[key]
        if new_colors == colors:
            break
        colors = new_colors
    hist = defaultdict(int)
    
    for c in tmp:
        hist[c] += 1
    signature += "|".join(f"{c}:{hist[c]}" for c in sorted(hist))
    return signature

In [3]:
from pathlib import Path
GRAPH_DIR = "./UD_Spanish-GSD"
# --------- CONFIG ---------
FOLDER = Path(GRAPH_DIR)
OUT_CSV = Path("isomorphic_groups_distances_1or0.csv")

In [4]:
import copy
from tqdm import tqdm

def get_graph_dataset(folder):
    
    iso_groups = defaultdict(set)

    for path in tqdm(folder.rglob("*.graphml")):
        G = load_graph(path)
        if G.number_of_nodes() < 10:
            continue
        sig = wl_tree_signature(G)
        iso_groups[sig].add(str(path))

        for edge in G.edges():

            copy_G = copy.deepcopy(G)
            copy_G = nx.contracted_edge(copy_G, edge, self_loops=False)
            sig = wl_tree_signature(copy_G)
            iso_groups[sig].add(f"({edge})-" + str(path))
            

    return iso_groups

In [5]:
groups = get_graph_dataset(FOLDER)

# --------- Write result ---------
with OUT_CSV.open("w", encoding="utf-8") as f:
    f.write("signature;count;files\n")
    for sig, files in groups.items():
        f.write(f"{sig};{len(files)};\"{'|'.join(files)}\"\n")

print(f"Done. Wrote {len(groups)} isomorphism classes to {OUT_CSV}")

0it [00:00, ?it/s]

14187it [01:39, 143.12it/s]

Done. Wrote 235932 isomorphism classes to isomorphic_groups_distances_1or0.csv

In [6]:
import pandas as pd

df = pd.read_csv("isomorphic_groups_distances_>10_contract.csv", sep=";")
df

,signature,count,files
0,"0_(7,):1|10_(11,):1|11_(1, 9, 10):1|1_(2, 2, 2...",1,UD_Spanish-GSD/es_gsd-ud-train_12948.graphml
1,"0_(1, 1, 1, 3, 5, 9):1|1_(0,):3|2_(3,):1|3_(0,...",1,"(('2', '1'))-UD_Spanish-GSD/es_gsd-ud-train_12..."
2,"0_(7,):2|1_(2, 2, 2, 4, 6, 9):1|2_(1,):3|3_(4,...",1,"(('2', '4'))-UD_Spanish-GSD/es_gsd-ud-train_12..."
3,"0_(7,):1|10_(1, 8, 9):1|1_(2, 2, 2, 4, 6, 10):...",1,"(('4', '3'))-UD_Spanish-GSD/es_gsd-ud-train_12..."
4,"0_(7,):1|1_(2, 2, 2, 4, 6, 9):1|2_(1,):3|3_(4,...",1,"(('4', '7'))-UD_Spanish-GSD/es_gsd-ud-train_12..."
...,...,...,...
235927,"0_(13,):3|10_(8, 9, 12):1|11_(12,):2|12_(10, 1...",1,"(('15', '14'))-UD_Spanish-GSD/es_gsd-ud-train_..."
235928,"0_(12,):3|10_(11,):2|11_(9, 10, 10):1|12_(0, 0...",2,"(('17', '16'))-UD_Spanish-GSD/es_gsd-ud-train_..."
235929,"0_(13,):3|10_(9, 12):1|11_(12,):2|12_(10, 11, ...",1,"(('22', '21'))-UD_Spanish-GSD/es_gsd-ud-train_..."
235930,"0_(12,):3|10_(11,):3|11_(9, 10, 10, 10):1|12_(...",1,"(('22', '25'))-UD_Spanish-GSD/es_gsd-ud-train_..."
235931,"0_(10,):3|10_(0, 0, 0, 12):1|11_(12,):1|12_(1,...",2,"(('25', '24'))-UD_Spanish-GSD/es_gsd-ud-train_..."

In [7]:
signature = df[df["count"]==10]["signature"][134907]
df[df["count"]==10]#["signature"][189848]

KeyError: 134907

In [ ]:
df[df["signature"] == signature]["files"].values[0].split("|")

['(5)-UD_Spanish-GSD/es_gsd-ud-train_6273.graphml',
 '(4)-UD_Spanish-GSD/es_gsd-ud-train_6863.graphml',
 '(4)-UD_Spanish-GSD/es_gsd-ud-train_6273.graphml',
 '(1)-UD_Spanish-GSD/es_gsd-ud-train_7887.graphml',
 '(2)-UD_Spanish-GSD/es_gsd-ud-train_7897.graphml',
 '(1)-UD_Spanish-GSD/es_gsd-ud-train_3901.graphml',
 '(6)-UD_Spanish-GSD/es_gsd-ud-train_1557.graphml',
 '(5)-UD_Spanish-GSD/es_gsd-ud-train_6863.graphml',
 '(3)-UD_Spanish-GSD/es_gsd-ud-train_2787.graphml',
 '(7)-UD_Spanish-GSD/es_gsd-ud-train_1557.graphml']

# Output codex for distances

In [10]:
# Compute WL-isomorphic pairs (distance 0) and single-edge-merge pairs (distance 1)
from itertools import combinations
from ast import literal_eval
import pandas as pd

def split_entries(entries):
    originals = []
    contracted = []
    for entry in entries:
        if entry.startswith("(") and ")-" in entry:
            edge_raw, path = entry.split(")-", 1)
            edge = literal_eval(edge_raw[1:])
            contracted.append((path, edge))
        else:
            originals.append(entry)
    return originals, contracted

distance0_pairs = []
distance1_pairs = []
seen_dist1 = set()

for sig, entries in groups.items():
    originals, contracted = split_entries(entries)

    if len(originals) >= 2:
        for a, b in combinations(sorted(originals), 2):
            distance0_pairs.append({"signature": sig, "tree_a": a, "tree_b": b})

    if originals and contracted:
        for source_path, edge in contracted:
            for target_path in originals:
                if source_path == target_path:
                    continue
                key = (source_path, target_path, edge)
                if key in seen_dist1:
                    continue
                seen_dist1.add(key)
                distance1_pairs.append({
                    "signature_after_merge": sig,
                    "tree_contracted": source_path,
                    "merged_edge": edge,
                    "tree_matched": target_path,
                })

print(f"distance 0 pairs: {len(distance0_pairs)}")
print(f"distance 1 pairs: {len(distance1_pairs)}")

distance0_df = pd.DataFrame(distance0_pairs)
distance1_df = pd.DataFrame(distance1_pairs)
distance0_df.head(), distance1_df.head()

distance 0 pairs: 3692
distance 1 pairs: 4890

(                                           signature  \
 0  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 1  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 2  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 3  0_(4,):1|1_(8,):3|2_(3, 8):1|3_(2,):1|4_(0, 6,...
 4  0_(4,):1|1_(8,):3|2_(3, 8):1|3_(2,):1|4_(0, 6,...

                                          tree_a  \
 0   UD_Spanish-GSD/es_gsd-ud-train_4330.graphml
 1   UD_Spanish-GSD/es_gsd-ud-train_4330.graphml
 2    UD_Spanish-GSD/es_gsd-ud-train_668.graphml
 3  UD_Spanish-GSD/es_gsd-ud-train_10222.graphml
 4  UD_Spanish-GSD/es_gsd-ud-train_10222.graphml

                                          tree_b
 0    UD_Spanish-GSD/es_gsd-ud-train_668.graphml
 1   UD_Spanish-GSD/es_gsd-ud-train_8337.graphml
 2   UD_Spanish-GSD/es_gsd-ud-train_8337.graphml
 3  UD_Spanish-GSD/es_gsd-ud-train_11094.graphml
 4  UD_Spanish-GSD/es_gsd-ud-train_11440.graphml  ,
                                signature_after_merge  \
 0  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 1  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 2  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 3  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...
 4  0_(3,):1|1_(2,):2|2_(1, 1, 8):1|3_(0, 5, 8):1|...

                                tree_contracted merged_edge  \
 0  UD_Spanish-GSD/es_gsd-ud-train_4976.graphml    (11, 12)
 1  UD_Spanish-GSD/es_gsd-ud-train_4976.graphml    (11, 12)
 2  UD_Spanish-GSD/es_gsd-ud-train_4976.graphml    (11, 12)
 3  UD_Spanish-GSD/es_gsd-ud-train_4976.graphml    (12, 13)
 4  UD_Spanish-GSD/es_gsd-ud-train_4976.graphml    (12, 13)

                                   tree_matched
 0   UD_Spanish-GSD/es_gsd-ud-train_668.graphml
 1  UD_Spanish-GSD/es_gsd-ud-train_4330.graphml
 2  UD_Spanish-GSD/es_gsd-ud-train_8337.graphml
 3   UD_Spanish-GSD/es_gsd-ud-train_668.graphml
 4  UD_Spanish-GSD/es_gsd-ud-train_4330.graphml  )

In [ ]:
distance0_df.sort_values(by=["signature"], ascending=False)

,signature,tree_a,tree_b
3603,"0_(9,):4|10_(11,):1|11_(9, 10):1|12_(2, 6, 9):...",UD_Spanish-GSD/es_gsd-ud-train_184.graphml,UD_Spanish-GSD/es_gsd-ud-train_8158.graphml
3426,"0_(9,):3|10_(9, 12):1|11_(12,):2|12_(10, 11, 1...",UD_Spanish-GSD/es_gsd-ud-train_2720.graphml,UD_Spanish-GSD/es_gsd-ud-train_7931.graphml
3425,"0_(9,):3|10_(9, 12):1|11_(12,):2|12_(10, 11, 1...",UD_Spanish-GSD/es_gsd-ud-train_2720.graphml,UD_Spanish-GSD/es_gsd-ud-train_5946.graphml
3427,"0_(9,):3|10_(9, 12):1|11_(12,):2|12_(10, 11, 1...",UD_Spanish-GSD/es_gsd-ud-train_5946.graphml,UD_Spanish-GSD/es_gsd-ud-train_7931.graphml
3661,"0_(9,):3|10_(9, 12):1|11_(12,):2|12_(10, 11, 1...",UD_Spanish-GSD/es_gsd-ud-train_4607.graphml,UD_Spanish-GSD/es_gsd-ud-train_9242.graphml
...,...,...,...
541,"0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...",UD_Spanish-GSD/es_gsd-ud-train_14035.graphml,UD_Spanish-GSD/es_gsd-ud-train_223.graphml
3612,"0_(1,):2|1_(0, 3):2|2_(3,):1|3_(1, 1, 2, 5):1|...",UD_Spanish-GSD/es_gsd-ud-train_4439.graphml,UD_Spanish-GSD/es_gsd-ud-train_7840.graphml
2757,"0_(1,):2|1_(0, 2):2|2_(1, 3, 5):2|3_(2,):2|4_(...",UD_Spanish-GSD/es_gsd-ud-train_1032.graphml,UD_Spanish-GSD/es_gsd-ud-train_11148.graphml
3601,"0_(1,):2|10_(1, 1, 2, 9, 9, 12):1|11_(12,):2|1...",UD_Spanish-GSD/es_gsd-ud-train_1184.graphml,UD_Spanish-GSD/es_gsd-ud-train_12662.graphml
3653,"0_(1, 1, 3):2|1_(0,):4|2_(3,):1|3_(0, 0, 2, 5)...",UD_Spanish-GSD/es_gsd-ud-train_13359.graphml,UD_Spanish-GSD/es_gsd-ud-train_5963.graphml

In [11]:
# Drop pairs whose phrases are too similar (adapted from phrase_distances.ipynb)
from functools import lru_cache

phrase_distance_threshold = 0.5  # keep pairs with >= this normalized Levenshtein distance

def levenshtein(a: str, b: str) -> int:
    if a == b:
        return 0
    if len(a) < len(b):
        a, b = b, a
    previous = list(range(len(b) + 1))
    for i, ca in enumerate(a, start=1):
        current = [i]
        for j, cb in enumerate(b, start=1):
            insert_cost = current[j - 1] + 1
            delete_cost = previous[j] + 1
            replace_cost = previous[j - 1] + (ca != cb)
            current.append(min(insert_cost, delete_cost, replace_cost))
        previous = current
    return previous[-1]

@lru_cache(maxsize=None)
def get_phrase_text(path: str) -> str:
    G = nx.read_graphml(path)
    return G.graph.get("phrase", "")

def filter_pairs_by_phrase(df, sig_col, a_col, b_col):
    kept = []
    for sig, sub in df.groupby(sig_col):
        paths = set(sub[a_col]) | set(sub[b_col])
        phrases = {p: get_phrase_text(p) for p in paths}
        max_len = max((len(text) for text in phrases.values()), default=0)
        norm = max(max_len, 1)
        for _, row in sub.iterrows():
            pa, pb = row[a_col], row[b_col]
            d = levenshtein(phrases[pa], phrases[pb]) / norm
            if d >= phrase_distance_threshold:
                rec = row.to_dict()
                rec["phrase_distance"] = d
                kept.append(rec)
    return pd.DataFrame(kept)

distance0_df_clean = filter_pairs_by_phrase(distance0_df, "signature", "tree_a", "tree_b")
distance1_df_clean = filter_pairs_by_phrase(distance1_df, "signature_after_merge", "tree_contracted", "tree_matched")

print(f"distance0 pairs before: {len(distance0_df)}, after phrase filter: {len(distance0_df_clean)}")
print(f"distance1 pairs before: {len(distance1_df)}, after phrase filter: {len(distance1_df_clean)}")

distance0_df_clean.head(), distance1_df_clean.head()

distance0 pairs before: 3692, after phrase filter: 365
distance1 pairs before: 4890, after phrase filter: 3829

(                                           signature  \
 0  0_(1, 1, 3):2|1_(0,):4|2_(3,):1|3_(0, 0, 2, 5)...
 1  0_(1,):2|1_(0, 3):2|2_(3,):1|3_(1, 1, 2, 5):1|...
 2  0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...
 3  0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...
 4  0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...

                                          tree_a  \
 0  UD_Spanish-GSD/es_gsd-ud-train_13359.graphml
 1   UD_Spanish-GSD/es_gsd-ud-train_4439.graphml
 2  UD_Spanish-GSD/es_gsd-ud-train_14035.graphml
 3  UD_Spanish-GSD/es_gsd-ud-train_14035.graphml
 4  UD_Spanish-GSD/es_gsd-ud-train_14035.graphml

                                         tree_b  phrase_distance
 0  UD_Spanish-GSD/es_gsd-ud-train_5963.graphml         0.750000
 1  UD_Spanish-GSD/es_gsd-ud-train_7840.graphml         0.789474
 2   UD_Spanish-GSD/es_gsd-ud-train_223.graphml         0.761905
 3  UD_Spanish-GSD/es_gsd-ud-train_3054.graphml         0.714286
 4  UD_Spanish-GSD/es_gsd-ud-train_5199.graphml         0.682540  ,
                                signature_after_merge  \
 0  0_(0, 2):2|1_(2,):4|2_(0, 1, 1, 4):2|3_(4,):4|...
 1  0_(0, 2):2|1_(2,):4|2_(0, 1, 1, 4):2|3_(4,):4|...
 2  0_(1, 1, 1, 3):2|1_(0,):6|2_(3,):2|3_(0, 0, 2,...
 3  0_(1, 1, 3):2|1_(0,):4|2_(3,):1|3_(0, 0, 2, 5)...
 4  0_(1, 1, 3):2|1_(0,):4|2_(3,):1|3_(0, 0, 2, 5)...

                                 tree_contracted merged_edge  \
 0    UD_Spanish-GSD/es_gsd-ud-train_833.graphml      (3, 2)
 1  UD_Spanish-GSD/es_gsd-ud-train_13631.graphml      (9, 8)
 2  UD_Spanish-GSD/es_gsd-ud-train_10186.graphml      (4, 1)
 3  UD_Spanish-GSD/es_gsd-ud-train_13332.graphml      (2, 1)
 4  UD_Spanish-GSD/es_gsd-ud-train_13332.graphml      (2, 1)

                                    tree_matched  phrase_distance
 0   UD_Spanish-GSD/es_gsd-ud-train_3568.graphml         0.588235
 1   UD_Spanish-GSD/es_gsd-ud-train_3568.graphml         0.647059
 2  UD_Spanish-GSD/es_gsd-ud-train_13957.graphml         0.809524
 3  UD_Spanish-GSD/es_gsd-ud-train_13359.graphml         0.688312
 4   UD_Spanish-GSD/es_gsd-ud-train_5963.graphml         0.740260  )

In [12]:
distance0_df_clean.sort_values(by=["signature"], ascending=False)

,signature,tree_a,tree_b,phrase_distance
364,"0_(9,):1|10_(11,):2|11_(9, 10, 10, 13):1|12_(1...",UD_Spanish-GSD/es_gsd-ud-train_11288.graphml,UD_Spanish-GSD/es_gsd-ud-train_4416.graphml,0.755556
363,"0_(8,):2|10_(8, 9):1|11_(12,):2|12_(8, 11, 11)...",UD_Spanish-GSD/es_gsd-ud-train_12739.graphml,UD_Spanish-GSD/es_gsd-ud-train_3672.graphml,0.788889
362,"0_(7,):1|10_(11,):3|11_(2, 9, 10, 10, 10):1|1_...",UD_Spanish-GSD/es_gsd-ud-train_11312.graphml,UD_Spanish-GSD/es_gsd-ud-train_14109.graphml,0.684685
361,"0_(7,):1|10_(11,):3|11_(2, 4, 9, 10, 10, 10):1...",UD_Spanish-GSD/es_gsd-ud-train_12543.graphml,UD_Spanish-GSD/es_gsd-ud-train_8196.graphml,0.800000
360,"0_(7,):1|10_(11,):2|11_(2, 7, 10, 10):1|1_(2,)...",UD_Spanish-GSD/es_gsd-ud-train_13915.graphml,UD_Spanish-GSD/es_gsd-ud-train_1519.graphml,0.778947
...,...,...,...,...
6,"0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...",UD_Spanish-GSD/es_gsd-ud-train_223.graphml,UD_Spanish-GSD/es_gsd-ud-train_5199.graphml,0.761905
7,"0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...",UD_Spanish-GSD/es_gsd-ud-train_3054.graphml,UD_Spanish-GSD/es_gsd-ud-train_5199.graphml,0.682540
3,"0_(1,):2|1_(0, 3):2|2_(3,):2|3_(1, 2, 5):2|4_(...",UD_Spanish-GSD/es_gsd-ud-train_14035.graphml,UD_Spanish-GSD/es_gsd-ud-train_3054.graphml,0.714286
1,"0_(1,):2|1_(0, 3):2|2_(3,):1|3_(1, 1, 2, 5):1|...",UD_Spanish-GSD/es_gsd-ud-train_4439.graphml,UD_Spanish-GSD/es_gsd-ud-train_7840.graphml,0.789474
0,"0_(1, 1, 3):2|1_(0,):4|2_(3,):1|3_(0, 0, 2, 5)...",UD_Spanish-GSD/es_gsd-ud-train_13359.graphml,UD_Spanish-GSD/es_gsd-ud-train_5963.graphml,0.750000

In [13]:
distance1_df_clean.drop_duplicates(subset=["tree_contracted", "tree_matched"]).sort_values(by=["signature_after_merge"], ascending=False).head(20)

,signature_after_merge,tree_contracted,merged_edge,tree_matched,phrase_distance
3827,"0_(9,):3|1_(2,):1|2_(1, 4, 9):1|3_(4,):2|4_(2,...",UD_Spanish-GSD/es_gsd-ud-train_1173.graphml,"(11, 12)",UD_Spanish-GSD/es_gsd-ud-train_6742.graphml,0.778947
3826,"0_(9,):3|10_(11,):2|11_(2, 9, 10, 10):1|1_(2,)...",UD_Spanish-GSD/es_gsd-ud-train_12154.graphml,"(4, 2)",UD_Spanish-GSD/es_gsd-ud-train_7836.graphml,0.796296
3824,"0_(9,):2|1_(2,):2|2_(1, 1, 4, 9):1|3_(4,):2|4_...",UD_Spanish-GSD/es_gsd-ud-train_1664.graphml,"(4, 3)",UD_Spanish-GSD/es_gsd-ud-train_5728.graphml,0.743243
3823,"0_(9,):2|1_(2,):2|2_(1, 1, 4, 9):1|3_(4,):2|4_...",UD_Spanish-GSD/es_gsd-ud-train_12300.graphml,"(8, 2)",UD_Spanish-GSD/es_gsd-ud-train_5728.graphml,0.743243
3821,"0_(8,):3|10_(11,):2|11_(1, 9, 10, 10):1|12_(1,...",UD_Spanish-GSD/es_gsd-ud-train_1546.graphml,"(19, 18)",UD_Spanish-GSD/es_gsd-ud-train_1620.graphml,0.649485
3820,"0_(8,):2|1_(3, 8, 9):1|2_(3,):3|3_(1, 2, 2, 2)...",UD_Spanish-GSD/es_gsd-ud-train_8659.graphml,"(7, 2)",UD_Spanish-GSD/es_gsd-ud-train_4610.graphml,0.709302
3819,"0_(8,):2|1_(2,):2|2_(1, 1, 3, 8):1|3_(2, 5):1|...",UD_Spanish-GSD/es_gsd-ud-train_9933.graphml,"(9, 2)",UD_Spanish-GSD/es_gsd-ud-train_7459.graphml,0.792079
3815,"0_(8,):2|10_(8, 9, 12):1|11_(12,):1|12_(10, 11...",UD_Spanish-GSD/es_gsd-ud-train_7273.graphml,"(18, 19)",UD_Spanish-GSD/es_gsd-ud-train_2583.graphml,0.754717
3814,"0_(8,):2|10_(1, 8, 8, 9, 9):1|11_(1,):2|1_(3, ...",UD_Spanish-GSD/es_gsd-ud-train_3923.graphml,"(15, 16)",UD_Spanish-GSD/es_gsd-ud-train_4241.graphml,0.730337
3813,"0_(7,):4|1_(2,):3|2_(1, 1, 1, 7):1|3_(4,):1|4_...",UD_Spanish-GSD/es_gsd-ud-train_4293.graphml,"(9, 2)",UD_Spanish-GSD/es_gsd-ud-train_8363.graphml,0.787500
3812,"0_(7,):4|1_(2,):2|2_(1, 1, 4, 9):1|3_(4,):1|4_...",UD_Spanish-GSD/es_gsd-ud-train_11752.graphml,"(4, 2)",UD_Spanish-GSD/es_gsd-ud-train_3649.graphml,0.742857
3810,"0_(7,):4|1_(2,):2|2_(1, 1, 4, 9):1|3_(4,):1|4_...",UD_Spanish-GSD/es_gsd-ud-train_3649.graphml,"(16, 15)",UD_Spanish-GSD/es_gsd-ud-train_8479.graphml,0.704762
3809,"0_(7,):4|1_(2,):2|2_(1, 1, 4, 8):1|3_(4,):1|4_...",UD_Spanish-GSD/es_gsd-ud-train_11291.graphml,"(4, 10)",UD_Spanish-GSD/es_gsd-ud-train_68.graphml,0.750000
3808,"0_(7,):4|1_(2,):1|2_(1, 4, 9):1|3_(4,):1|4_(2,...",UD_Spanish-GSD/es_gsd-ud-train_3649.graphml,"(11, 9)",UD_Spanish-GSD/es_gsd-ud-train_2012.graphml,0.780952
3807,"0_(7,):3|1_(2,):2|2_(1, 1, 4, 7):1|3_(4,):1|4_...",UD_Spanish-GSD/es_gsd-ud-train_8237.graphml,"(2, 5)",UD_Spanish-GSD/es_gsd-ud-train_6757.graphml,0.722772
3806,"0_(7,):3|1_(2,):2|2_(1, 1, 4, 7):1|3_(4,):1|4_...",UD_Spanish-GSD/es_gsd-ud-train_8479.graphml,"(5, 2)",UD_Spanish-GSD/es_gsd-ud-train_6757.graphml,0.574257
3805,"0_(7,):2|1_(2,):6|2_(1, 1, 1, 7):2|3_(4,):2|4_...",UD_Spanish-GSD/es_gsd-ud-train_1525.graphml,"(2, 4)",UD_Spanish-GSD/es_gsd-ud-train_13309.graphml,0.716981
3804,"0_(7,):2|1_(2,):3|2_(1, 1, 1, 4, 6, 7):1|3_(4,...",UD_Spanish-GSD/es_gsd-ud-train_13211.graphml,"(4, 3)",UD_Spanish-GSD/es_gsd-ud-train_12973.graphml,0.715789
3802,"0_(7,):2|1_(2, 2, 2, 2, 4, 6, 9):1|2_(1,):4|3_...",UD_Spanish-GSD/es_gsd-ud-train_8325.graphml,"(4, 3)",UD_Spanish-GSD/es_gsd-ud-train_4865.graphml,0.771739
3801,"0_(7,):2|10_(11,):3|11_(9, 10, 10, 10):1|1_(2,...",UD_Spanish-GSD/es_gsd-ud-train_6741.graphml,"(11, 10)",UD_Spanish-GSD/es_gsd-ud-train_7871.graphml,0.708333